create table food (
      id bigint generated by default as identity (start with 1)
    , name varchar(255)
    , description varchar(255) 
    , primary key (id)
);

insert into food(id, name, description) values (default, 'Palacsinta', 'Folyékony tésztából készített, serpenyőben mindkét oldalán megsütött, tésztája ízesítése szerint édes vagy sós étel.');
insert into food(id, name, description) values (default, 'Tiramisu', 'Olasz desszert.');
